name: mac-build

on:
  push:
    branches: ["master", "linux"]
  pull_request:
    branches: ["master", "linux"]

permissions:
  contents: write

jobs:
  build:

    runs-on: macos-14

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Select Xcode 14.3.1 for macOS 11 Compatibility
        run: sudo xcode-select -s /Applications/Xcode_14.3.1.app/Contents/Developer --version

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Build Environment
        run: |
          echo "CC=gcc" >> $GITHUB_ENV
          echo "CXX=g++" >> $GITHUB_ENV

      - name: Configure
        run: cmake -G "Unix Makefiles" -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"

      - name: Build
        run: cmake --build build --config Release


      - name: Debug Output Directory
        run: |
          ls -la
          ls -la build/
          # Tip: If your binary goes to a subfolder like 'bin', you can verify it here:
          # ls -la build/bin/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: CAFFeinated-macOS
          path: build/bin/CAFFeinated.app
          if-no-files-found: error

      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/bin/CAFFeinated.app
          fail_on_unmatched_files: true
          generate_release_notes: true
